# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'miniproject.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(737, 613)
        Form.setMaximumSize(QtCore.QSize(737, 16777215))
        Form.setStyleSheet("background-image: url(:/newPrefix/bg2.jpg);")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 201, 61))
        self.pushButton.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 0, 201, 61))
        self.pushButton_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 0, 201, 61))
        self.pushButton_3.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(0, 60, 541, 391))
        self.listView.setStyleSheet("background-image: url(:/newPrefix/music-headphones-minimalist-hd-wallpaper-preview.jpg);")
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 460, 321, 51))
        self.label.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(540, 250, 201, 61))
        self.pushButton_4.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(540, 90, 201, 61))
        self.pushButton_5.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(540, 170, 201, 61))
        self.pushButton_6.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(240, 140, 201, 61))
        self.pushButton_8.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(240, 210, 201, 61))
        self.pushButton_9.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(240, 350, 201, 61))
        self.pushButton_10.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(240, 280, 201, 61))
        self.pushButton_11.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(240, 420, 201, 61))
        self.pushButton_12.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(240, 280, 201, 61))
        self.pushButton_13.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(240, 140, 201, 61))
        self.pushButton_14.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Form)
        self.pushButton_15.setGeometry(QtCore.QRect(240, 420, 201, 61))
        self.pushButton_15.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Form)
        self.pushButton_16.setGeometry(QtCore.QRect(240, 350, 201, 61))
        self.pushButton_16.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(Form)
        self.pushButton_17.setGeometry(QtCore.QRect(240, 210, 201, 61))
        self.pushButton_17.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(Form)
        self.pushButton_18.setGeometry(QtCore.QRect(240, 420, 201, 61))
        self.pushButton_18.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(Form)
        self.pushButton_19.setGeometry(QtCore.QRect(240, 280, 201, 61))
        self.pushButton_19.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(Form)
        self.pushButton_20.setGeometry(QtCore.QRect(240, 140, 201, 61))
        self.pushButton_20.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(Form)
        self.pushButton_21.setGeometry(QtCore.QRect(240, 210, 201, 61))
        self.pushButton_21.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(Form)
        self.pushButton_22.setGeometry(QtCore.QRect(240, 350, 201, 61))
        self.pushButton_22.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_22.setObjectName("pushButton_22")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(130, 520, 501, 41))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_18.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.listView.raise_()
        self.label.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.pushButton_15.raise_()
        self.pushButton_16.raise_()
        self.pushButton_17.raise_()
        self.pushButton_19.raise_()
        self.pushButton_20.raise_()
        self.pushButton_21.raise_()
        self.pushButton_22.raise_()
        self.comboBox.raise_()

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(self.listView.show) # type: ignore
        self.pushButton.clicked.connect(self.label.show) # type: ignore
        self.pushButton_3.clicked.connect(self.listView.close) # type: ignore
        self.pushButton_3.clicked.connect(self.label.close) # type: ignore
        self.pushButton_2.clicked.connect(self.listView.close) # type: ignore
        self.pushButton_2.clicked.connect(self.label.close) # type: ignore
        self.pushButton_3.clicked.connect(self.pushButton_5.show) # type: ignore
        self.pushButton_3.clicked.connect(self.pushButton_6.show) # type: ignore
        self.pushButton_3.clicked.connect(self.pushButton_4.show) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_5.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_6.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_4.close) # type: ignore
        self.pushButton_2.clicked.connect(self.pushButton_5.close) # type: ignore
        self.pushButton_2.clicked.connect(self.pushButton_6.close) # type: ignore
        self.pushButton_2.clicked.connect(self.pushButton_4.close) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_8.show) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_9.show) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_11.show) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_10.show) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_12.show) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_8.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_9.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_11.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_10.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_12.close) # type: ignore
        self.pushButton_3.clicked.connect(self.pushButton_8.close) # type: ignore
        self.pushButton_3.clicked.connect(self.pushButton_9.close) # type: ignore
        self.pushButton_3.clicked.connect(self.pushButton_11.close) # type: ignore
        self.pushButton_3.clicked.connect(self.pushButton_10.close) # type: ignore
        self.pushButton_3.clicked.connect(self.pushButton_12.close) # type: ignore
        self.pushButton_2.clicked.connect(self.pushButton_8.close) # type: ignore
        self.pushButton_2.clicked.connect(self.pushButton_9.close) # type: ignore
        self.pushButton_2.clicked.connect(self.pushButton_11.close) # type: ignore
        self.pushButton_2.clicked.connect(self.pushButton_10.close) # type: ignore
        self.pushButton_2.clicked.connect(self.pushButton_12.close) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_14.show) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_17.show) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_13.show) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_16.show) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_15.show) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_14.close) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_17.close) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_13.close) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_16.close) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_15.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_14.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_17.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_13.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_16.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_15.close) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_14.close) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_17.close) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_13.close) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_16.close) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_15.close) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_8.close) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_9.close) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_11.close) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_10.close) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_12.close) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_8.close) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_9.close) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_11.close) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_10.close) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_12.close) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_20.show) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_21.show) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_19.show) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_22.show) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_18.show) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_20.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_21.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_21.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_19.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_22.close) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_18.close) # type: ignore
        self.pushButton_3.clicked.connect(self.pushButton_20.close) # type: ignore
        self.pushButton_3.clicked.connect(self.pushButton_21.close) # type: ignore
        self.pushButton_3.clicked.connect(self.pushButton_19.close) # type: ignore
        self.pushButton_3.clicked.connect(self.pushButton_22.close) # type: ignore
        self.pushButton_3.clicked.connect(self.pushButton_18.close) # type: ignore
        self.pushButton_2.clicked.connect(self.pushButton_20.close) # type: ignore
        self.pushButton_2.clicked.connect(self.pushButton_21.close) # type: ignore
        self.pushButton_2.clicked.connect(self.pushButton_19.close) # type: ignore
        self.pushButton_2.clicked.connect(self.pushButton_22.close) # type: ignore
        self.pushButton_2.clicked.connect(self.pushButton_18.close) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_20.close) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_21.close) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_19.close) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_22.close) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_18.close) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_20.close) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_21.close) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_19.close) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_22.close) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_18.close) # type: ignore
        self.pushButton_2.clicked.connect(self.comboBox.show) # type: ignore
        self.pushButton.clicked.connect(self.comboBox.close) # type: ignore
        self.pushButton_3.clicked.connect(self.comboBox.close) # type: ignore
        self.pushButton_5.clicked.connect(self.comboBox.close) # type: ignore
        self.pushButton_6.clicked.connect(self.comboBox.close) # type: ignore
        self.pushButton_4.clicked.connect(self.comboBox.close) # type: ignore
        self.ShowName()
        QtCore.QMetaObject.connectSlotsByName(Form)

    def ShowName(self) :

                name_id = []
                self.db = pymysql.connect(host="127.0.0.1", database="name", user="root", password="1234", charset="utf8")
                self.cur = self.db.cursor()
                self.cur.execute('SELECT * FROM name_id;')
                data = self.cur.fetchall()
                for i in data :
                        self.comboBox.addItem(i[1])
                        self.comboBox.addItem(i[0])

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Main Page"))
        self.pushButton_2.setText(_translate("Form", "About us"))
        self.pushButton_3.setText(_translate("Form", "MenuPage"))
        self.label.setText(_translate("Form", "welcome to the music world"))
        self.pushButton_4.setText(_translate("Form", "HIP-HOP"))
        self.pushButton_5.setText(_translate("Form", "K-POP"))
        self.pushButton_6.setText(_translate("Form", "POP"))
        self.pushButton_8.setText(_translate("Form", "BLACKPINK"))
        self.pushButton_9.setText(_translate("Form", "BTS"))
        self.pushButton_10.setText(_translate("Form", "SEVENTEEN"))
        self.pushButton_11.setText(_translate("Form", "TWICE"))
        self.pushButton_12.setText(_translate("Form", "EXO"))
        self.pushButton_13.setText(_translate("Form", "JUSTIN "))
        self.pushButton_14.setText(_translate("Form", "LADY GAGA"))
        self.pushButton_15.setText(_translate("Form", "MADONNA"))
        self.pushButton_16.setText(_translate("Form", "RIHANNA"))
        self.pushButton_17.setText(_translate("Form", "KESHA"))
        self.pushButton_18.setText(_translate("Form", "JOEY BOY"))
        self.pushButton_19.setText(_translate("Form", "SOUTHSIDE"))
        self.pushButton_20.setText(_translate("Form", "URBOY TJ"))
        self.pushButton_21.setText(_translate("Form", "ILLSLICK"))
        self.pushButton_22.setText(_translate("Form", "THAITANIUM"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
